version: '3.8'

services:
  web:
    build:
      context: .
      target: nginx
    ports:
      - "9090:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      target: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    command: >
      sh -c "pip install -r requirements.txt &&
             flask run --host=0.0.0.0 --port=5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge